spring:
  application:
    name: league-of-legends-ai-chat
  datasource:
    url: jdbc:h2:mem:lc24
    driver-class-name: org.h2.Driver
    user: sa
    password: ''
  h2:
    console:
      enabled: true